extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: error
scope: heading
match: $sentence
indicators:
  - ":"
exceptions:
  - About Apollo's reference
  - API
  - Apollo Client DevTools
  - Apollo Client Web
  - Apollo Federation
  - Apollo GraphOS
  - Apollo iOS
  - Apollo Kotlin
  - Apollo Organization
  - Apollo Router
  - Apollo Server
  - AWS
  - Azure (AD)?
  - Bookmark Apps?
  - CI(/CD)?
  - CLI
  - Cloud Dedicated
  - CNAME
  - "Configur(e|ation|ing)"
  - Connect APIs
  - Contribute to Apollo
  - CORS
  - Cosmos
  - Create an Apollo account
  - Create an Azure AD app registration
  - Datadog Metrics Explorer
  - Docker
  - Emmet
  - "[Ee]nterprise"
  - Elastic License v2
  - Explorer
  - Express
  - FAQ
  - Federation (1|2)
  - Fractional sampling
  - GDPR
  - GitHub
  - GraphOS
  - GraphOS Cloud on AWS
  - GraphOS Studio
  - GraphQL
  - GraphQL Summit
  - Go live
  - gRPC
  - How can Apollo help address requests from Data Subjects?
  - HTTP
  - I
  - IAM
  - IDs?
  - Kubernetes
  - Linux
  - macOS
  - Markdown
  - Marketplace
  - MongoDB
  - Notify Apollo
  - OpenTelemetry Collector
  - PingOne
  - PRs?
  - REPL
  - REST
  - "[Rr]eport(ing)?"
  - Rover
  - SAF
  - Safari
  - SAML
  - Sandbox
  - SDL
  - SDUI
  - Send OIDC metadata
  - Send SAML metadata
  - Studio
  - TypeScript
  - UI
  - URLs?
  - VPC Lattice
  - Visual
  - VS
  - WebSockets?
  - Windows
  - Zipkin
