extends: substitution
message: "Use '%s' instead of '%s'."
link: "https://docs.google.com/document/d/1jZhBYPgoZsxe5UEMD3oaGHISoxo6DFR7oJxNij0i6X8/edit#heading=h.2r6oe67u29eb"
level: error
ignorecase: false
action:
  name: replace
swap:
  "(?:API Console|dev|developer) key": API key
  "(?:cell ?phone|smart ?phone)": phone|mobile phone
  "(?:dev|developer|APIs) console": API console
  "(?:e-mail|E-mail)": email
  "(?:file ?path|path ?name)": path
  "(?:kill|terminate|abort)": stop|exit|cancel|end
  "(?:OAuth ?2|Oauth)": OAuth 2.0
  "(?:ok|Okay)": OK|okay
  "(?:WiFi|wifi)": Wi-Fi
  '[.]+apk': APK
  '3-D': 3D
  "apollo Gateway": "@apollo/gateway"
  "apollo Studio": GraphOS Studio
  "back-end": backend
  "chapter": documents|pages|sections
  "check box": checkbox
  "click on": click|click in
  "Container Engine": Kubernetes Engine
  "content type": media type
  "curated roles": predefined roles
  "day": day
  "deviation": deviation
  "dialog": dialog
  "disabled?": turn off|off
  "enterprise plan": Enterprise plan
  "ephemeral IP address": ephemeral external IP address
  "file name": filename
  "firewalls": firewall rules
  "free plan": Free plan
  "front-end": frontend
  "Github": GitHub
  "Google account": Google Account
  "Google accounts": Google Accounts
  "Googling": search with Google
  "grayed-out": unavailable
  "HTTPs": HTTPS
  "homepage": homepage
  "in order to": to
  "javascript": JavaScript
  "k8s": Kubernetes
  "long press": touch & hold
  "network IP address": internal IP address
  "NodeJS": Node.js
  "omnibox": address bar
  "overview screen": recents screen
  "regex": regular expression
  "schema checks": schema checks
  "SHA1": SHA-1|HAS-SHA1
  "sign into": sign in to
  "single sign on": single sign-on
  "static IP address": static external IP address
  "stylesheet": style sheet
  "synch": sync
  "towards": toward
  "the CLI": the Rover CLI
  "the Router": the Apollo Router
  "the Sandbox": "Apollo Sandbox"
  "Typescript": TypeScript
  "URL": URL
  "url": URL
  "vs.": versus
  "World Wide Web": web