# mapping of local source paths to the location of their content
# TODO: maybe try sourcing content from outside the src directory?
# https://github.com/gatsbyjs/gatsby/issues/5510
/: src/content/basics
graphos: src/content/graphos/basics
graphos/metrics: src/content/graphos/metrics
graphos/security: src/content/graphos/security
graphos/delivery: src/content/graphos/delivery
graphos/org: src/content/graphos/org
technotes: src/content/technotes
community: src/content/community
odyssey: src/content/odyssey
